import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as vscode from 'vscode';
import { StorageManager } from '../types';
import { logger } from '../utils/logger';

const STARTUP_DIR = path.join(os.homedir(), '.ipython', 'profile_default', 'startup');
const STARTUP_FILE = path.join(STARTUP_DIR, '00_api_vault.py');
const IS_WINDOWS = process.platform === 'win32';
const SHELL_ENV_FILE = path.join(
    os.homedir(),
    IS_WINDOWS ? '.secrets_manager_env.ps1' : '.secrets_manager_env.sh'
);
// Global .env file — the single source of truth for notebook secrets.
// The IPython watcher script monitors this file and updates os.environ live.
const DOTENV_FILE = path.join(os.homedir(), '.secrets_manager.env');

/**
 * The IPython startup script content.
 * Instead of hardcoding secret values, this installs a background file-watcher
 * that monitors ~/.secrets_manager.env and syncs os.environ within ~1 second
 * of any change — no kernel restart required after the first install.
 */
const WATCHER_SCRIPT = `\
# Secrets Manager — Auto-generated by the Secrets Manager VS Code extension.
# Do not edit manually. Toggle secrets in the Secrets Manager sidebar.
import os as _sm_os, threading as _sm_t, time as _sm_time

_SM_FILE = _sm_os.path.expanduser('~/.secrets_manager.env')
_sm_mtime = [None]
_sm_tracked = set()

def _sm_reload():
    try:
        exists = _sm_os.path.exists(_SM_FILE)
        mt = _sm_os.path.getmtime(_SM_FILE) if exists else 0
        if mt == _sm_mtime[0]:
            return
        _sm_mtime[0] = mt
        new_keys = set()
        if exists:
            with open(_SM_FILE) as _f:
                for _line in _f:
                    _line = _line.strip()
                    if _line and not _line.startswith('#') and '=' in _line:
                        _k, _, _v = _line.partition('=')
                        _sm_os.environ[_k.strip()] = _v
                        new_keys.add(_k.strip())
        for _k in (_sm_tracked - new_keys):
            _sm_os.environ.pop(_k, None)
        _sm_tracked.clear()
        _sm_tracked.update(new_keys)
    except Exception:
        pass

def _sm_watch():
    while True:
        _sm_time.sleep(1)
        _sm_reload()

_sm_reload()
_sm_t.Thread(target=_sm_watch, daemon=True, name='secrets-manager').start()
del _sm_watch
`;

/**
 * Ensures the IPython startup watcher script exists and updates
 * ~/.secrets_manager.env with the currently active notebook keys.
 * Running kernels pick up changes within ~1 second automatically.
 */
export async function updateStartupScript(storage: StorageManager): Promise<void> {
    const keys = await storage.getKeys();
    const activeKeys = keys.filter(k => k.notebookAccess);

    if (activeKeys.length === 0) {
        clearStartupScript();
        return;
    }

    // Ensure the IPython startup directory exists
    if (!fs.existsSync(STARTUP_DIR)) {
        fs.mkdirSync(STARTUP_DIR, { recursive: true });
    }

    // Write the watcher script (static — same content every time)
    try {
        fs.writeFileSync(STARTUP_FILE, WATCHER_SCRIPT, { mode: 0o600, encoding: 'utf8' });
        try { logger.storage(`IPython watcher script updated at: ${STARTUP_FILE}`); } catch {}
    } catch (err) {
        try { logger.error('Failed to write IPython startup script', err as Error); } catch {}
        console.error('[Secrets Manager] Failed to write IPython startup script', err);
    }

    // Write the .env file — this is what the watcher (and python.envFile) reads
    const dotenvLines: string[] = ['# Secrets Manager — Auto-generated for VS Code Jupyter kernels.'];
    for (const key of activeKeys) {
        const value = await storage.getValue(key.name);
        if (value) {
            const safe = value.replace(/\r?\n/g, '\\n');
            dotenvLines.push(`${key.name}=${safe}`);
        }
    }
    dotenvLines.push('');
    try {
        fs.writeFileSync(DOTENV_FILE, dotenvLines.join('\n'), { mode: 0o600, encoding: 'utf8' });
        // Point VS Code Python/Jupyter extension to this file for non-IPython kernels
        const pythonConfig = vscode.workspace.getConfiguration('python');
        await pythonConfig.update('envFile', DOTENV_FILE, vscode.ConfigurationTarget.Global);
    } catch (err) {
        console.error('[Secrets Manager] Failed to write .env file', err);
    }

    // Write a shell export file so plain `python script.py` can source it
    const shellLines: string[] = IS_WINDOWS
        ? [
            '# Secrets Manager — Auto-generated. Run this in PowerShell to use secrets in Python.',
            '# Add to your PowerShell profile:  . ~/.secrets_manager_env.ps1',
            '',
          ]
        : [
            '# Secrets Manager — Auto-generated. Source this to use secrets in any shell/Python.',
            '# Add to ~/.zshrc or ~/.bashrc:  source ~/.secrets_manager_env.sh',
            '',
          ];
    for (const key of activeKeys) {
        const value = await storage.getValue(key.name);
        if (value) {
            if (IS_WINDOWS) {
                const safe = value.replace(/'/g, "''");
                shellLines.push(`$env:${key.name} = '${safe}'`);
            } else {
                const safe = value.replace(/\\/g, '\\\\').replace(/'/g, "'\\''");
                shellLines.push(`export ${key.name}='${safe}'`);
            }
        }
    }
    shellLines.push('');
    try {
        const writeOpts: fs.WriteFileOptions = IS_WINDOWS
            ? { encoding: 'utf8' }
            : { mode: 0o600, encoding: 'utf8' };
        fs.writeFileSync(SHELL_ENV_FILE, shellLines.join('\n'), writeOpts);
    } catch (err) {
        console.error('[Secrets Manager] Failed to write shell env file', err);
    }
}

/**
 * Deletes the startup script and all generated env files.
 * Called when all notebook access is cleared or the extension deactivates.
 */
export function clearStartupScript(): void {
    for (const file of [STARTUP_FILE, SHELL_ENV_FILE, DOTENV_FILE]) {
        if (fs.existsSync(file)) {
            try {
                fs.unlinkSync(file);
            } catch (err) {
                console.error('[Secrets Manager] Failed to clear file', file, err);
            }
        }
    }
    try { logger.storage('Startup scripts cleared'); } catch {}
}

export { STARTUP_FILE };

/**
 * Syncs active secrets into VS Code's environmentVariableCollection so they
 * are automatically available in every new integrated terminal.
 */
export async function updateTerminalEnv(
    context: vscode.ExtensionContext,
    storage: StorageManager
): Promise<void> {
    const keys = await storage.getKeys();
    context.environmentVariableCollection.clear();
    for (const key of keys) {
        if (key.terminalAccess) {
            const value = await storage.getValue(key.name);
            if (value) {
                context.environmentVariableCollection.replace(key.name, value);
            }
        }
    }
    context.environmentVariableCollection.description =
        'Secrets Manager: active secrets injected into all terminals';
}

/**
 * Immediately injects or removes a secret in all running Jupyter kernels
 * by executing Python code via the Jupyter extension API.
 * Tries both the new API (v2: api.kernels) and old API (api.getKernelService).
 * Falls back to a "Restart Kernel" notification if no kernel is reachable.
 */
export async function injectIntoRunningNotebooks(
    storage: StorageManager,
    keyName: string
): Promise<void> {
    const notebooks = vscode.workspace.notebookDocuments;
    if (notebooks.length === 0) { return; }

    const keys = await storage.getKeys();
    const key = keys.find(k => k.name === keyName);
    if (!key) { return; }

    let code: string;
    if (key.notebookAccess) {
        const value = await storage.getValue(keyName);
        if (!value) { return; }
        const safe = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
        code = `import os; os.environ['${keyName}'] = '${safe}'`;
    } else {
        code = `import os; os.environ.pop('${keyName}', None)`;
    }

    const jupyterExt = vscode.extensions.getExtension<any>('ms-toolsai.jupyter');
    if (!jupyterExt) {
        _showRestartNotification();
        return;
    }

    try {
        const api = jupyterExt.isActive ? jupyterExt.exports : await jupyterExt.activate();
        if (!api) { _showRestartNotification(); return; }

        let injected = false;
        for (const doc of notebooks) {
            // Try new Jupyter API (v2+): api.kernels.getKernel(uri)
            let kernel = api.kernels?.getKernel?.(doc.uri)?.kernel;

            // Fall back to old API: api.getKernelService() -> getKernelByUri(uri)
            if (!kernel) {
                try {
                    const svc = await api.getKernelService?.();
                    kernel = svc?.getKernelByUri?.(doc.uri) ?? svc?.getKernel?.(doc.uri)?.kernel;
                } catch { /* old API not available */ }
            }

            if (!kernel) { continue; }

            try {
                const cts = new vscode.CancellationTokenSource();
                const gen = kernel.executeCode?.(code, `sm-${Date.now()}`, cts.token);
                if (gen) { for await (const _ of gen) { /* consume */ } }
                cts.dispose();
                injected = true;
            } catch { /* per-kernel error, skip */ }
        }

        if (!injected) { _showRestartNotification(); }
    } catch { _showRestartNotification(); }
}

function _showRestartNotification(): void {
    vscode.window.showInformationMessage(
        'Secrets Manager: Restart your Jupyter kernel to apply secret changes.',
        'Restart Kernel'
    ).then(action => {
        if (action === 'Restart Kernel') {
            vscode.commands.executeCommand('jupyter.restartkernel');
        }
    });
}

/**
 * Immediately injects or removes a secret in all currently open integrated
 * terminals via sendText — no terminal restart required.
 */
export async function injectIntoExistingTerminals(
    storage: StorageManager,
    keyName: string
): Promise<void> {
    const keys = await storage.getKeys();
    const key = keys.find(k => k.name === keyName);
    if (!key) { return; }

    let cmd: string;
    if (key.terminalAccess) {
        const value = await storage.getValue(keyName);
        if (!value) { return; }
        if (IS_WINDOWS) {
            const safe = value.replace(/'/g, "''");
            cmd = `$env:${keyName} = '${safe}'`;
        } else {
            const safe = value.replace(/\\/g, '\\\\').replace(/'/g, "'\\''");
            cmd = `export ${keyName}='${safe}'`;
        }
    } else {
        cmd = IS_WINDOWS
            ? `Remove-Item Env:${keyName} -ErrorAction SilentlyContinue`
            : `unset ${keyName}`;
    }

    vscode.window.terminals.forEach(terminal => terminal.sendText(cmd));
}
